// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vszyairiwwjefycarpsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZzenlhaXJpd3dqZWZ5Y2FycHNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNTU2NzMsImV4cCI6MjA1NTkzMTY3M30.dXtrn-FXCrTJSemeD0OgRjV0F3SNDHmHOH_vwApR50k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);